version: '3.9'

services:
  grpc_db:
    image: postgres:14
    container_name: grpc_db
    environment:
      - POSTGRES_USER=grpc_user
      - POSTGRES_PASSWORD=grpc_password

  grpc_server:
    build: ./server
    container_name: grpc_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - grpc_db
  